### ISSUE TITLE
Nobs UX is bad news

### ISSUE THREAD

**Issue by garfbargle** [bitgapp/new-eqmac-archive#2]
First off, thank you for this new release! 

2nd, I about had a heart attack trying when i tried to adjust the volume nob and it suddenly went to max volume and my house was shaking. Although it looks pretty, the UI is not meant for a mouse.

**Comment by nodeful** [comment]
I do agree the knobs aren't the best UX, I do however learnt to use the mouse wheel / trackpad 2 finger scroll to adjust the knobs instead of clicking and dragging. I will try and make an option to replace all knobs with sliders.

**Comment by enaluz** [comment]
I would recommend an option to completely switch out knobs and dials and simply input numbers via a text input. This would allow people to get really specific with their setups, make it easier to remember/save (perhaps even in JSON format), and easily change. Personally I'm all for doing away with complex UIs if possible, in favor of function > form (without necessarily having to compromise on attractiveness). Thoughts?

**Comment by nodeful** [comment]
@enaluz this would have to be an optional feature that is not enabled by default. Most people prefer convenient and pretty UI's over 100% utility. As mentioned before I will try to make that option a reality in the future.

**Comment by nodeful** [comment]
Hey everyone 👋 
I will be open sourcing the new version of eqMac, therefore, I am closing this issue and repository as I will be transfering [nodeful/eqMac2](https://github.com/nodeful/eqMac2) repo to [bitgapp/eqMac](https://github.com/bitgapp/eqMac)
Please bear with me for the next couple of days as I setup that new repo. The eqMac2 code will be living in the [old-eqMac2](https://github.com/bitgapp/eqMac/tree/old-eqmac2) branch if anyone is interested in referencing it for whatever reason.
Please try out the new version and report bugs to the new repo.
Thanks for using eqMac.

**Comment by nodeful** [comment]
![image](https://user-images.githubusercontent.com/8472525/79671511-97e18800-81c2-11ea-8e6e-678c6dbcd730.png)
I have added an option to replace knobs with sliders now. I can see it in the Settings dropdown. No need to update, just restart eqMac and it should be there.
Just a reminder this repo is now archived and moved to https://github.com/bitgapp/eqMac
